name: Build VSCode Extension

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/upload-artifact@v2

      - name: Set up Node.js
        uses: actions/upload-artifact@v2

        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install vsce
        run: npm install -g @vscode/vsce

      - name: Package extension
        run: vsce package
      - name: Upload .vsix artifact
        uses: actions/upload-artifact@v2
        with:
          name: extension
          path: '*.vsix'
