name: Build VSCode Extension

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install vsce globally
        run: npm install -g vsce

      - name: Package Extension
        run: vsce package

      - name: Upload VSIX artifact
        uses: actions/upload-artifact@v3
        with:
          name: vscode-extension
          path: '*.vsix'
